name: mobile_catch_a_ride
description: The Mobile Front-end for the Catch-A-Ride  application

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_polyline_points: ^1.0.0
  google_maps_flutter: ^2.1.2
  cupertino_icons: ^1.0.2
  geolocator: ^8.2.0
  dio: ^4.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

