name: Docker Build, Test, APK release

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: |
        docker-compose up -d
        ls -la
#        docker cp $(docker ps -a -q):./mobile_catch_a_ride/build/app/outputs/apk/release/ ./built_releases

    - name: Copy Docker APK to host
      run: |
        ls -la
        echo "=================[ NEW CALL ]================="
        ls -la $(docker ps -a -q):./mobile_catch_a_ride/build/app/outputs/apk/release/

    - name: Release APKs
      uses: softprops/action-gh-release@v0.1.5
      if: startsWith(github.ref, 'refs/tags/')
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        files: |
          mobile_catch_a_ride/build/app/outputs/apk/release/
#          $(docker ps -a -q):./mobile_catch_a_ride/build/app/outputs/apk/release/

#     - name: Release bundle
#       uses: softprops/action-gh-release@v0.1.5
#       if: startsWith(github.ref, 'refs/tags/')
#       env:
#         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#       with:
#         files: $(docker ps -a -q):./mobile_catch_a_ride/build/app/outputs/bundle/release/
