name: Docker Build, Test, APK release

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker-compose up -d

#     - name: Copy Docker APK to host
#       run: docker cp $(docker ps -a -q):./mobile_catch_a_ride/build/app/outputs/apk/release/release/app-release.apk ./

    - name: Release APKs
      uses: softprops/action-gh-release@v0.1.5
      if: startsWith(github.ref, 'refs/tags/')
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
#         files: app-release.apk
        files: $(docker ps -a -q):./mobile_catch_a_ride/build/app/outputs/apk/release/

#     - name: Release bundle
#       uses: softprops/action-gh-release@v0.1.5
#       if: startsWith(github.ref, 'refs/tags/')
#       env:
#         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#       with:
#         files: $(docker ps -a -q):./mobile_catch_a_ride/build/app/outputs/bundle/release/
