name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  test:
    runs-on: ubuntu-latest
    steps:
    - uses: docker/build-push-action@v2
    - name: Build Flutter Docker Image
      with:
        file: ./mobile_catch_a_ride/Dockerfile
        push: true
        pull: false
        tag: user/app:latest
#       run: docker-compose up -d
