name: Docker Build, Test, APK release

env:
  USER: Henry

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker-compose up -d

    - uses: actions/upload-artifact@v3
      with:
        name: APK-releases
        path: $(docker ps -a -q):/home/$USER/mobile_catch_a_ride/build/app/outputs/apk/release
        if-no-files-found: error

    - uses: actions/upload-artifact@v3
      with:
        name: bundle-releases
        path: $(docker ps -a -q):/home/$USER/mobile_catch_a_ride/build/app/outputs/bundle/release
        if-no-files-found: error


    - uses: softprops/action-gh-release@v0.1.5

    - uses: actions/download-artifact@v3

    - name: Release APKs
      if: startsWith(github.ref, 'refs/tags/')
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        files: |
          ./bundle-release
          ./APK-release
