name: Docker Build, Test, APK release

env:
  USER: Henry

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: |
        docker-compose up -d
        mkdir built_releases
        docker ps -a -q
        docker cp $(docker ps -a -q):/home/$USER/mobile_catch_a_ride/build/app/outputs/ ./built_releases
        ls -la mobile_catch_a_ride
        ls -la mobile_catch_a_ride/built_releases

    - uses: actions/checkout@v2
    - name: Testing finding files
      run: |
        ls -la mobile_catch_a_ride
        echo "=========================================================="
        ls -la mobile_catch_a_ride/built_releases

    - name: Release APKs
      uses: softprops/action-gh-release@v0.1.5
      if: startsWith(github.ref, 'refs/tags/')
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        files: |
          mobile_catch_a_ride/build/app/outputs/apk/release/
          mobile_catch_a_ride/build/app/outputs/bundle/release/
#          $(docker ps -a -q):./mobile_catch_a_ride/build/app/outputs/apk/release/

#     - name: Release bundle
#       uses: softprops/action-gh-release@v0.1.5
#       if: startsWith(github.ref, 'refs/tags/')
#       env:
#         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#       with:
#         files: $(docker ps -a -q):./mobile_catch_a_ride/build/app/outputs/bundle/release/
