name: Docker Build, Test, APK release

env:
  USER: Henry

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  Build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker-compose up -d

    - name: finding files
      run: |
        ls -la $(docker ps -a -q):/home/$USER/mobile_catch_a_ride/build/app/outputs/apk/release

    - uses: actions/upload-artifact@v3
      with:
        name: APK-releases
        path: $(docker ps -a -q):/home/$USER/mobile_catch_a_ride/build/app/outputs/apk/release
        if-no-files-found: error

    - uses: actions/upload-artifact@v3
      with:
        name: bundle-releases
        path: $(docker ps -a -q):/home/$USER/mobile_catch_a_ride/build/app/outputs/bundle/release
        if-no-files-found: error


#   Release:
#     needs: [Build]
#     runs-on: ubuntu-latest

#     steps:
#     - uses: softprops/action-gh-release@v0.1.5

#     - uses: actions/download-artifact@v3

#     - name: Release APKs
#       if: startsWith(github.ref, 'refs/tags/')
#       env:
#         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#       with:
#         files: |
#           ./bundle-release
#           ./APK-release
  

#   Cleanup:
#     needs: [Build, Release]
#     if: always()
#     runs-on: ubuntu-latest

#     steps:
#     - name: call webhook to delete artifacts
#       env:
#         FOR_WEBHOOKS_SECRET: ${{ secrets.WEBHOOKS_SECRET }}
#       run: |
#         echo "::add-mask::$FOR_WEBHOOKS_SECRET"
#         curl --verbose --fail --show-error --location --request POST "https://api.github.com/repos/$GITHUB_REPOSITORY/dispatches" --header "Authorization: token $FOR_WEBHOOKS_SECRET" --header 'Content-Type: application/json' --header 'Accept: application/vnd.github.everest-preview+json' --data-raw "{ \"event_type\": \"delete_all_artifacts\", \"client_payload\": {\"parent_runid\": \"$GITHUB_RUN_ID\", \"parent_repo\": \"$GITHUB_REPOSITORY\"} }"
